import { GlobalConfig } from 'payload'
import all from '@/collections/access/all'
import admin from '@/collections/access/admin'

export const CalculatorSectionSettings: GlobalConfig = {
  slug: 'calculator',
  label: 'Настройки секции калькулятора',
  access: {
    read: all,
    update: admin,
    readDrafts: all,
    readVersions: all,
  },
  fields: [
    {
      label: 'Main',
      name: 'main',
      type: 'group',
      fields: [
        {
          name: 'inputs',
          label: 'Inputs',
          type: 'group',
          fields: [
            {
              name: 'length',
              label: 'Length',
              type: 'text',
              required: true,
              localized: true,
              defaultValue: '0',
            },
            {
              name: 'width',
              label: 'Width',
              type: 'text',
              required: true,
              localized: true,
              defaultValue: '0',
            },
            {
              name: 'stories',
              label: 'Stories',
              type: 'group',
              localized: true,
              fields: [
                {
                  name: 'label',
                  label: 'Label',
                  type: 'text',
                  required: true,
                  localized: true,
                  defaultValue: 'Default Label',
                },
                {
                  name: 'oneStory',
                  label: 'One Story',
                  type: 'text',
                  required: true,
                  localized: true,
                  defaultValue: 'Default One Story',
                },
                {
                  name: 'twoStory',
                  label: 'Two Story',
                  type: 'text',
                  required: true,
                  localized: true,
                  defaultValue: 'Default Two Story',
                },
                {
                  name: 'oneStoryPF',
                  label: 'One Story PF',
                  type: 'text',
                  required: true,
                  localized: true,
                  defaultValue: 'Default One Story PF',
                },
                {
                  name: 'twoStoryPF',
                  label: 'Two Story PF',
                  type: 'text',
                  required: true,
                  localized: true,
                  defaultValue: 'Default Two Story PF',
                },
              ],
            },
          ],
        },
        {
          name: 'buttons',
          label: 'Buttons',
          type: 'group',
          fields: [
            {
              name: 'advancedMode',
              label: 'Advanced Mode',
              type: 'text',
              required: true,
              localized: true,
              defaultValue: 'Default Advanced Mode',
            },
            {
              name: 'reset',
              label: 'Reset',
              type: 'text',
              required: true,
              localized: true,
              defaultValue: 'Default Reset',
            },
          ],
        },
        {
          name: 'output',
          label: 'Output',
          type: 'group',
          fields: [
            {
              name: 'buildingArea',
              label: 'Building Area',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Building Area',
            },
            {
              name: 'usableArea',
              label: 'Usable Area',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Usable Area',
            },
            {
              name: 'buildingWeight',
              label: 'Building Weight',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Building Weight',
            },
            {
              name: 'weightOnTheFoundation',
              label: 'Weight on the Foundation',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Weight on the Foundation',
            },
            {
              name: 'heatLoss',
              label: 'Heat Loss',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Heat Loss',
            },
            {
              name: 'minHeatingPower',
              label: 'Min Heating Power',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Min Heating Power',
            },
            {
              name: 'heatingCosts',
              label: 'Heating Costs',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Heating Costs',
            },
            {
              name: 'price',
              label: 'Price',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Price',
            },
            {
              name: 'pricePerSq2',
              label: 'Price per sq^2',
              type: 'text',
              localized: true,
              required: true,
              defaultValue: 'Default Price per sq^2',
            },
          ],
        },
        {
          name: 'buildingPolygon',
          label: 'Building Polygon',
          type: 'group',
          fields: [
            {
              name: 'width',
              label: 'Width',
              type: 'text',
              admin: { description: '$$ -- the width of the building in meters' },
              required: true,
              localized: true,
              validate: (value?: string | null) =>
                value?.includes('$$') ? true : "Should include '$$'",
              defaultValue: '0 $$',
            },
            {
              name: 'length',
              label: 'Length',
              type: 'text',
              admin: { description: '$$ -- the width of the building in meters' },
              required: true,
              localized: true,
              validate: (value?: string | null) =>
                value?.includes('$$') ? true : "Should include '$$'",
              defaultValue: '0 $$',
            },
            {
              name: 'stories',
              label: 'Stories',
              type: 'group',
              fields: [
                {
                  name: 'oneStory',
                  label: 'One Story',
                  type: 'text',
                  localized: true,
                  required: true,
                  defaultValue: 'Default One Story',
                },
                {
                  name: 'twoStory',
                  label: 'Two Story',
                  type: 'text',
                  localized: true,
                  required: true,
                  defaultValue: 'Default Two Story',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
